Object.defineProperty(exports,"__esModule",{value:true});var _this8=this;exports.























checkMfa=checkMfa;exports.
















login=login;exports.






























































loadMe=loadMe;exports.


















































































logout=logout;exports.








getProfiles=getProfiles;exports.





























getProfilesByIds=getProfilesByIds;exports.









getProfilesInTeam=getProfilesInTeam;exports.
































getProfilesInChannel=getProfilesInChannel;exports.


































getProfilesNotInChannel=getProfilesNotInChannel;exports.


































getUser=getUser;exports.









getUserByUsername=getUserByUsername;exports.





















getStatusesByIdsBatchedDebounced=getStatusesByIdsBatchedDebounced;exports.




getStatusesByIds=getStatusesByIds;exports.









getSessions=getSessions;exports.









loadProfilesForDirect=loadProfilesForDirect;exports.



























revokeSession=revokeSession;exports.









getAudits=getAudits;exports.









autocompleteUsersInChannel=autocompleteUsersInChannel;exports.




























searchProfiles=searchProfiles;exports.





























































startPeriodicStatusUpdates=startPeriodicStatusUpdates;exports.























stopPeriodicStatusUpdates=stopPeriodicStatusUpdates;exports.







updateUserNotifyProps=updateUserNotifyProps;var _reduxBatchedActions=require('redux-batched-actions');var _client=require('../client');var _client2=_interopRequireDefault(_client);var _constants=require('../constants');var _channel_utils=require('../utils/channel_utils');var _errors=require('./errors');var _helpers=require('./helpers');var _preferences=require('./preferences');var _teams=require('./teams');function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{default:obj};}function _toConsumableArray(arr){if(Array.isArray(arr)){for(var i=0,arr2=Array(arr.length);i<arr.length;i++){arr2[i]=arr[i];}return arr2;}else{return Array.from(arr);}}function checkMfa(loginId){var _this=this;return function _callee(dispatch,getState){var mfa;return regeneratorRuntime.async(function _callee$(_context){while(1){switch(_context.prev=_context.next){case 0:dispatch({type:_constants.UsersTypes.CHECK_MFA_REQUEST},getState);_context.prev=1;_context.next=4;return regeneratorRuntime.awrap(_client2.default.checkMfa(loginId));case 4:mfa=_context.sent;dispatch({type:_constants.UsersTypes.CHECK_MFA_SUCCESS},getState);return _context.abrupt('return',mfa);case 9:_context.prev=9;_context.t0=_context['catch'](1);dispatch((0,_reduxBatchedActions.batchActions)([{type:_constants.UsersTypes.CHECK_MFA_FAILURE,error:_context.t0},(0,_errors.getLogErrorAction)(_context.t0)]),getState);return _context.abrupt('return',null);case 13:case'end':return _context.stop();}}},null,_this,[[1,9]]);};}function login(loginId,password){var _this2=this;var mfaToken=arguments.length>2&&arguments[2]!==undefined?arguments[2]:'';return function _callee3(dispatch,getState){var deviceId;return regeneratorRuntime.async(function _callee3$(_context3){while(1){switch(_context3.prev=_context3.next){case 0:dispatch({type:_constants.UsersTypes.LOGIN_REQUEST},getState);deviceId=getState().entities.general.deviceToken;return _context3.abrupt('return',_client2.default.login(loginId,password,mfaToken,deviceId).then(function _callee2(data){var teamMembers,preferences,teamMembersRequest,preferencesRequest;return regeneratorRuntime.async(function _callee2$(_context2){while(1){switch(_context2.prev=_context2.next){case 0:teamMembers=void 0;preferences=void 0;_context2.prev=2;teamMembersRequest=_client2.default.getMyTeamMembers();preferencesRequest=_client2.default.getMyPreferences();_context2.next=7;return regeneratorRuntime.awrap(teamMembersRequest);case 7:teamMembers=_context2.sent;_context2.next=10;return regeneratorRuntime.awrap(preferencesRequest);case 10:preferences=_context2.sent;_context2.next=17;break;case 13:_context2.prev=13;_context2.t0=_context2['catch'](2);dispatch((0,_reduxBatchedActions.batchActions)([{type:_constants.UsersTypes.LOGIN_FAILURE,error:_context2.t0},(0,_errors.getLogErrorAction)(_context2.t0)]),getState);return _context2.abrupt('return');case 17:_context2.prev=17;_context2.next=20;return regeneratorRuntime.awrap((0,_teams.fetchTeams)()(dispatch,getState));case 20:_context2.next=27;break;case 22:_context2.prev=22;_context2.t1=_context2['catch'](17);(0,_helpers.forceLogoutIfNecessary)(_context2.t1,dispatch);dispatch((0,_reduxBatchedActions.batchActions)([{type:_constants.UsersTypes.LOGIN_FAILURE,error:_context2.t1},(0,_errors.getLogErrorAction)(_context2.t1)]),getState);return _context2.abrupt('return');case 27:_context2.t2=dispatch;_context2.t3=_reduxBatchedActions.batchActions;_context2.t4={type:_constants.UsersTypes.RECEIVED_ME,data:data};_context2.t5=_constants.PreferencesTypes.RECEIVED_PREFERENCES;_context2.next=33;return regeneratorRuntime.awrap(preferences);case 33:_context2.t6=_context2.sent;_context2.t7={type:_context2.t5,data:_context2.t6};_context2.t8=_constants.TeamsTypes.RECEIVED_MY_TEAM_MEMBERS;_context2.next=38;return regeneratorRuntime.awrap(teamMembers);case 38:_context2.t9=_context2.sent;_context2.t10={type:_context2.t8,data:_context2.t9};_context2.t11={type:_constants.UsersTypes.LOGIN_SUCCESS};_context2.t12=[_context2.t4,_context2.t7,_context2.t10,_context2.t11];_context2.t13=(0,_context2.t3)(_context2.t12);_context2.t14=getState;(0,_context2.t2)(_context2.t13,_context2.t14);case 45:case'end':return _context2.stop();}}},null,_this2,[[2,13],[17,22]]);}).catch(function(error){dispatch((0,_reduxBatchedActions.batchActions)([{type:_constants.UsersTypes.LOGIN_FAILURE,error:error},(0,_errors.getLogErrorAction)(error)]),getState);return;}));case 3:case'end':return _context3.stop();}}},null,_this2);};}function loadMe(){var _this3=this;return function _callee4(dispatch,getState){var user,deviceId,preferences,teamMembers;return regeneratorRuntime.async(function _callee4$(_context4){while(1){switch(_context4.prev=_context4.next){case 0:user=void 0;dispatch({type:_constants.UsersTypes.LOGIN_REQUEST},getState);_context4.prev=2;_context4.next=5;return regeneratorRuntime.awrap(_client2.default.getMe());case 5:user=_context4.sent;_context4.next=13;break;case 8:_context4.prev=8;_context4.t0=_context4['catch'](2);(0,_helpers.forceLogoutIfNecessary)(_context4.t0,dispatch);dispatch((0,_reduxBatchedActions.batchActions)([{type:_constants.UsersTypes.LOGIN_FAILURE,error:_context4.t0},(0,_errors.getLogErrorAction)(_context4.t0)]),getState);return _context4.abrupt('return');case 13:deviceId=getState().entities.general.deviceToken;if(deviceId){_client2.default.attachDevice(deviceId);}preferences=void 0;dispatch({type:_constants.PreferencesTypes.MY_PREFERENCES_REQUEST},getState);_context4.prev=17;_context4.next=20;return regeneratorRuntime.awrap(_client2.default.getMyPreferences());case 20:preferences=_context4.sent;_context4.next=28;break;case 23:_context4.prev=23;_context4.t1=_context4['catch'](17);(0,_helpers.forceLogoutIfNecessary)(_context4.t1,dispatch);dispatch((0,_reduxBatchedActions.batchActions)([{type:_constants.PreferencesTypes.MY_PREFERENCES_FAILURE,error:_context4.t1},(0,_errors.getLogErrorAction)(_context4.t1)]),getState);return _context4.abrupt('return');case 28:_context4.prev=28;_context4.next=31;return regeneratorRuntime.awrap((0,_teams.fetchTeams)()(dispatch,getState));case 31:_context4.next=38;break;case 33:_context4.prev=33;_context4.t2=_context4['catch'](28);(0,_helpers.forceLogoutIfNecessary)(_context4.t2,dispatch);dispatch((0,_reduxBatchedActions.batchActions)([{type:_constants.TeamsTypes.FETCH_TEAMS_FAILURE,error:_context4.t2},(0,_errors.getLogErrorAction)(_context4.t2)]),getState);return _context4.abrupt('return');case 38:teamMembers=void 0;dispatch({type:_constants.TeamsTypes.MY_TEAM_MEMBERS_REQUEST},getState);_context4.prev=40;_context4.next=43;return regeneratorRuntime.awrap(_client2.default.getMyTeamMembers());case 43:teamMembers=_context4.sent;_context4.next=51;break;case 46:_context4.prev=46;_context4.t3=_context4['catch'](40);(0,_helpers.forceLogoutIfNecessary)(_context4.t3,dispatch);dispatch((0,_reduxBatchedActions.batchActions)([{type:_constants.TeamsTypes.MY_TEAM_MEMBERS_FAILURE,error:_context4.t3},(0,_errors.getLogErrorAction)(_context4.t3)]),getState);return _context4.abrupt('return');case 51:dispatch((0,_reduxBatchedActions.batchActions)([{type:_constants.UsersTypes.RECEIVED_ME,data:user},{type:_constants.UsersTypes.LOGIN_SUCCESS},{type:_constants.PreferencesTypes.RECEIVED_PREFERENCES,data:preferences},{type:_constants.PreferencesTypes.MY_PREFERENCES_SUCCESS},{type:_constants.TeamsTypes.RECEIVED_MY_TEAM_MEMBERS,data:teamMembers},{type:_constants.TeamsTypes.MY_TEAM_MEMBERS_SUCCESS}]),getState);case 52:case'end':return _context4.stop();}}},null,_this3,[[2,8],[17,23],[28,33],[40,46]]);};}function logout(){return(0,_helpers.bindClientFunc)(_client2.default.logout,_constants.UsersTypes.LOGOUT_REQUEST,_constants.UsersTypes.LOGOUT_SUCCESS,_constants.UsersTypes.LOGOUT_FAILURE);}function getProfiles(offset){var _this4=this;var limit=arguments.length>1&&arguments[1]!==undefined?arguments[1]:_constants.Constants.PROFILE_CHUNK_SIZE;return function _callee5(dispatch,getState){var profiles;return regeneratorRuntime.async(function _callee5$(_context5){while(1){switch(_context5.prev=_context5.next){case 0:dispatch({type:_constants.UsersTypes.PROFILES_REQUEST},getState);profiles=void 0;_context5.prev=2;_context5.next=5;return regeneratorRuntime.awrap(_client2.default.getProfiles(offset,limit));case 5:profiles=_context5.sent;_context5.next=13;break;case 8:_context5.prev=8;_context5.t0=_context5['catch'](2);(0,_helpers.forceLogoutIfNecessary)(_context5.t0,dispatch);dispatch((0,_reduxBatchedActions.batchActions)([{type:_constants.UsersTypes.PROFILES_FAILURE,error:_context5.t0},(0,_errors.getLogErrorAction)(_context5.t0)]),getState);return _context5.abrupt('return',null);case 13:dispatch((0,_reduxBatchedActions.batchActions)([{type:_constants.UsersTypes.RECEIVED_PROFILES,data:profiles},{type:_constants.UsersTypes.PROFILES_SUCCESS}]),getState);return _context5.abrupt('return',profiles);case 15:case'end':return _context5.stop();}}},null,_this4,[[2,8]]);};}function getProfilesByIds(userIds){return(0,_helpers.bindClientFunc)(_client2.default.getProfilesByIds,_constants.UsersTypes.PROFILES_REQUEST,[_constants.UsersTypes.RECEIVED_PROFILES,_constants.UsersTypes.PROFILES_SUCCESS],_constants.UsersTypes.PROFILES_FAILURE,userIds);}function getProfilesInTeam(teamId,offset){var _this5=this;var limit=arguments.length>2&&arguments[2]!==undefined?arguments[2]:_constants.Constants.PROFILE_CHUNK_SIZE;return function _callee6(dispatch,getState){var profiles;return regeneratorRuntime.async(function _callee6$(_context6){while(1){switch(_context6.prev=_context6.next){case 0:dispatch({type:_constants.UsersTypes.PROFILES_IN_TEAM_REQUEST},getState);profiles=void 0;_context6.prev=2;_context6.next=5;return regeneratorRuntime.awrap(_client2.default.getProfilesInTeam(teamId,offset,limit));case 5:profiles=_context6.sent;_context6.next=13;break;case 8:_context6.prev=8;_context6.t0=_context6['catch'](2);(0,_helpers.forceLogoutIfNecessary)(_context6.t0,dispatch);dispatch((0,_reduxBatchedActions.batchActions)([{type:_constants.UsersTypes.PROFILES_IN_TEAM_FAILURE,error:_context6.t0},(0,_errors.getLogErrorAction)(_context6.t0)]),getState);return _context6.abrupt('return');case 13:dispatch((0,_reduxBatchedActions.batchActions)([{type:_constants.UsersTypes.RECEIVED_PROFILES_IN_TEAM,data:profiles,id:teamId},{type:_constants.UsersTypes.RECEIVED_PROFILES,data:profiles},{type:_constants.UsersTypes.PROFILES_IN_TEAM_SUCCESS}]),getState);case 14:case'end':return _context6.stop();}}},null,_this5,[[2,8]]);};}function getProfilesInChannel(teamId,channelId,offset){var _this6=this;var limit=arguments.length>3&&arguments[3]!==undefined?arguments[3]:_constants.Constants.PROFILE_CHUNK_SIZE;return function _callee7(dispatch,getState){var currentUserId,profiles;return regeneratorRuntime.async(function _callee7$(_context7){while(1){switch(_context7.prev=_context7.next){case 0:currentUserId=getState().entities.users.currentUserId;dispatch({type:_constants.UsersTypes.PROFILES_IN_CHANNEL_REQUEST},getState);profiles=void 0;_context7.prev=3;_context7.next=6;return regeneratorRuntime.awrap(_client2.default.getProfilesInChannel(teamId,channelId,offset,limit));case 6:profiles=_context7.sent;Reflect.deleteProperty(profiles,currentUserId);_context7.next=15;break;case 10:_context7.prev=10;_context7.t0=_context7['catch'](3);(0,_helpers.forceLogoutIfNecessary)(_context7.t0,dispatch);dispatch((0,_reduxBatchedActions.batchActions)([{type:_constants.UsersTypes.PROFILES_IN_CHANNEL_FAILURE,error:_context7.t0},(0,_errors.getLogErrorAction)(_context7.t0)]),getState);return _context7.abrupt('return');case 15:dispatch((0,_reduxBatchedActions.batchActions)([{type:_constants.UsersTypes.RECEIVED_PROFILES_IN_CHANNEL,data:profiles,id:channelId},{type:_constants.UsersTypes.RECEIVED_PROFILES,data:profiles},{type:_constants.UsersTypes.PROFILES_IN_CHANNEL_SUCCESS}]),getState);case 16:case'end':return _context7.stop();}}},null,_this6,[[3,10]]);};}function getProfilesNotInChannel(teamId,channelId,offset){var _this7=this;var limit=arguments.length>3&&arguments[3]!==undefined?arguments[3]:_constants.Constants.PROFILE_CHUNK_SIZE;return function _callee8(dispatch,getState){var currentUserId,profiles;return regeneratorRuntime.async(function _callee8$(_context8){while(1){switch(_context8.prev=_context8.next){case 0:currentUserId=getState().entities.users.currentUserId;dispatch({type:_constants.UsersTypes.PROFILES_NOT_IN_CHANNEL_REQUEST},getState);profiles=void 0;_context8.prev=3;_context8.next=6;return regeneratorRuntime.awrap(_client2.default.getProfilesNotInChannel(teamId,channelId,offset,limit));case 6:profiles=_context8.sent;Reflect.deleteProperty(profiles,currentUserId);_context8.next=15;break;case 10:_context8.prev=10;_context8.t0=_context8['catch'](3);(0,_helpers.forceLogoutIfNecessary)(_context8.t0,dispatch);dispatch((0,_reduxBatchedActions.batchActions)([{type:_constants.UsersTypes.PROFILES_NOT_IN_CHANNEL_FAILURE,error:_context8.t0},(0,_errors.getLogErrorAction)(_context8.t0)]),getState);return _context8.abrupt('return');case 15:dispatch((0,_reduxBatchedActions.batchActions)([{type:_constants.UsersTypes.RECEIVED_PROFILES_NOT_IN_CHANNEL,data:profiles,id:channelId},{type:_constants.UsersTypes.RECEIVED_PROFILES,data:profiles},{type:_constants.UsersTypes.PROFILES_NOT_IN_CHANNEL_SUCCESS}]),getState);case 16:case'end':return _context8.stop();}}},null,_this7,[[3,10]]);};}function getUser(id){return(0,_helpers.bindClientFunc)(_client2.default.getUser,_constants.UsersTypes.USER_REQUEST,[_constants.UsersTypes.RECEIVED_PROFILE,_constants.UsersTypes.USER_SUCCESS],_constants.UsersTypes.USER_FAILURE,id);}function getUserByUsername(username){return(0,_helpers.bindClientFunc)(_client2.default.getUserByUsername,_constants.UsersTypes.USER_BY_USERNAME_REQUEST,[_constants.UsersTypes.RECEIVED_PROFILE,_constants.UsersTypes.USER_BY_USERNAME_SUCCESS],_constants.UsersTypes.USER_BY_USERNAME_FAILURE,username);}var ids=[];var debouncedGetStatusesByIds=(0,_helpers.debounce)(function _callee9(dispatch,getState){return regeneratorRuntime.async(function _callee9$(_context9){while(1){switch(_context9.prev=_context9.next){case 0:getStatusesByIds([].concat(_toConsumableArray(new Set(ids))))(dispatch,getState);case 1:case'end':return _context9.stop();}}},null,_this8);},20,false,function(){ids=[];});function getStatusesByIdsBatchedDebounced(id){ids=[].concat(_toConsumableArray(ids),[id]);return debouncedGetStatusesByIds;}function getStatusesByIds(userIds){return(0,_helpers.bindClientFunc)(_client2.default.getStatusesByIds,_constants.UsersTypes.PROFILES_STATUSES_REQUEST,[_constants.UsersTypes.RECEIVED_STATUSES,_constants.UsersTypes.PROFILES_STATUSES_SUCCESS],_constants.UsersTypes.PROFILES_STATUSES_FAILURE,userIds);}function getSessions(userId){return(0,_helpers.bindClientFunc)(_client2.default.getSessions,_constants.UsersTypes.SESSIONS_REQUEST,[_constants.UsersTypes.RECEIVED_SESSIONS,_constants.UsersTypes.SESSIONS_SUCCESS],_constants.UsersTypes.SESSIONS_FAILURE,userId);}function loadProfilesForDirect(){var _this9=this;return function _callee10(dispatch,getState){var state,_state$entities$chann,channels,myMembers,myPreferences,currentUserId,values,i,channel,member,otherUserId;return regeneratorRuntime.async(function _callee10$(_context10){while(1){switch(_context10.prev=_context10.next){case 0:state=getState();_state$entities$chann=state.entities.channels,channels=_state$entities$chann.channels,myMembers=_state$entities$chann.myMembers;myPreferences=state.entities.preferences.myPreferences;currentUserId=state.entities.users.currentUserId;values=Object.values(channels);i=0;case 6:if(!(i<values.length)){_context10.next=15;break;}channel=values[i];member=myMembers[channel.id];if(!(!(0,_channel_utils.isDirectChannel)(channel)&&!(0,_channel_utils.isGroupChannel)(channel))){_context10.next=11;break;}return _context10.abrupt('continue',12);case 11:if(member){if(member.mention_count>0&&(0,_channel_utils.isDirectChannel)(channel)&&!(0,_channel_utils.isDirectChannelVisible)(currentUserId,myPreferences,channel)){otherUserId=(0,_channel_utils.getUserIdFromChannelName)(currentUserId,channel.name);(0,_preferences.makeDirectChannelVisibleIfNecessary)(otherUserId)(dispatch,getState);}else if((member.mention_count>0||member.msg_count<channel.total_msg_count)&&(0,_channel_utils.isGroupChannel)(channel)&&!(0,_channel_utils.isGroupChannelVisible)(myPreferences,channel)){(0,_preferences.makeGroupMessageVisibleIfNecessary)(channel.id)(dispatch,getState);}}case 12:i++;_context10.next=6;break;case 15:case'end':return _context10.stop();}}},null,_this9);};}function revokeSession(id){return(0,_helpers.bindClientFunc)(_client2.default.revokeSession,_constants.UsersTypes.REVOKE_SESSION_REQUEST,[_constants.UsersTypes.RECEIVED_REVOKED_SESSION,_constants.UsersTypes.REVOKE_SESSION_SUCCESS],_constants.UsersTypes.REVOKE_SESSION_FAILURE,id);}function getAudits(userId){return(0,_helpers.bindClientFunc)(_client2.default.getAudits,_constants.UsersTypes.AUDITS_REQUEST,[_constants.UsersTypes.RECEIVED_AUDITS,_constants.UsersTypes.AUDITS_SUCCESS],_constants.UsersTypes.AUDITS_FAILURE,userId);}function autocompleteUsersInChannel(teamId,channelId,term){var _this10=this;return function _callee11(dispatch,getState){var data;return regeneratorRuntime.async(function _callee11$(_context11){while(1){switch(_context11.prev=_context11.next){case 0:dispatch({type:_constants.UsersTypes.AUTOCOMPLETE_IN_CHANNEL_REQUEST},getState);data=void 0;_context11.prev=2;_context11.next=5;return regeneratorRuntime.awrap(_client2.default.autocompleteUsersInChannel(teamId,channelId,term));case 5:data=_context11.sent;_context11.next=13;break;case 8:_context11.prev=8;_context11.t0=_context11['catch'](2);(0,_helpers.forceLogoutIfNecessary)(_context11.t0,dispatch);dispatch((0,_reduxBatchedActions.batchActions)([{type:_constants.UsersTypes.AUTOCOMPLETE_IN_CHANNEL_FAILURE,error:_context11.t0},(0,_errors.getLogErrorAction)(_context11.t0)]),getState);return _context11.abrupt('return');case 13:dispatch((0,_reduxBatchedActions.batchActions)([{type:_constants.UsersTypes.RECEIVED_AUTOCOMPLETE_IN_CHANNEL,data:data,channelId:channelId},{type:_constants.UsersTypes.AUTOCOMPLETE_IN_CHANNEL_SUCCESS}]),getState);case 14:case'end':return _context11.stop();}}},null,_this10,[[2,8]]);};}function searchProfiles(term){var _this11=this;var options=arguments.length>1&&arguments[1]!==undefined?arguments[1]:{};return function _callee12(dispatch,getState){var currentUserId,profiles,search,actions;return regeneratorRuntime.async(function _callee12$(_context12){while(1){switch(_context12.prev=_context12.next){case 0:currentUserId=getState().entities.users.currentUserId;dispatch({type:_constants.UsersTypes.SEARCH_PROFILES_REQUEST},getState);profiles={};search=void 0;_context12.prev=4;_context12.next=7;return regeneratorRuntime.awrap(_client2.default.searchProfiles(term,options));case 7:search=_context12.sent;search.forEach(function(p){if(p.id!==currentUserId){profiles[p.id]=p;}});_context12.next=16;break;case 11:_context12.prev=11;_context12.t0=_context12['catch'](4);(0,_helpers.forceLogoutIfNecessary)(_context12.t0,dispatch);dispatch((0,_reduxBatchedActions.batchActions)([{type:_constants.UsersTypes.SEARCH_PROFILES_FAILURE,error:_context12.t0},(0,_errors.getLogErrorAction)(_context12.t0)]),getState);return _context12.abrupt('return',null);case 16:actions=[{type:_constants.UsersTypes.RECEIVED_PROFILES,data:profiles}];if(options.in_channel_id){actions.push({type:_constants.UsersTypes.RECEIVED_PROFILES_IN_CHANNEL,data:profiles,id:options.in_channel_id});}if(options.not_in_channel_id){actions.push({type:_constants.UsersTypes.RECEIVED_PROFILES_NOT_IN_CHANNEL,data:profiles,id:options.not_in_channel_id});}if(options.team_id){actions.push({type:_constants.UsersTypes.RECEIVED_PROFILES_IN_TEAM,data:profiles,id:options.team_id});}dispatch((0,_reduxBatchedActions.batchActions)([].concat(actions,[{type:_constants.UsersTypes.SEARCH_PROFILES_SUCCESS}])),getState);return _context12.abrupt('return',profiles);case 22:case'end':return _context12.stop();}}},null,_this11,[[4,11]]);};}var statusIntervalId='';function startPeriodicStatusUpdates(){var _this12=this;return function _callee13(dispatch,getState){return regeneratorRuntime.async(function _callee13$(_context13){while(1){switch(_context13.prev=_context13.next){case 0:clearInterval(statusIntervalId);statusIntervalId=setInterval(function(){var statuses=getState().entities.users.statuses;if(!statuses){return;}var userIds=Object.keys(statuses);if(!userIds.length){return;}getStatusesByIds(userIds)(dispatch,getState);},_constants.Constants.STATUS_INTERVAL);case 2:case'end':return _context13.stop();}}},null,_this12);};}function stopPeriodicStatusUpdates(){var _this13=this;return function _callee14(){return regeneratorRuntime.async(function _callee14$(_context14){while(1){switch(_context14.prev=_context14.next){case 0:if(statusIntervalId){clearInterval(statusIntervalId);}case 1:case'end':return _context14.stop();}}},null,_this13);};}function updateUserNotifyProps(notifyProps){var _this14=this;
return function _callee15(dispatch,getState){var data;return regeneratorRuntime.async(function _callee15$(_context15){while(1){switch(_context15.prev=_context15.next){case 0:
dispatch({type:_constants.UsersTypes.UPDATE_NOTIFY_PROPS_REQUEST},getState);

data=void 0;_context15.prev=2;_context15.next=5;return regeneratorRuntime.awrap(

_client2.default.updateUserNotifyProps(notifyProps));case 5:data=_context15.sent;_context15.next=12;break;case 8:_context15.prev=8;_context15.t0=_context15['catch'](2);

dispatch({type:_constants.UsersTypes.UPDATE_NOTIFY_PROPS_FAILURE,error:_context15.t0},getState);return _context15.abrupt('return');case 12:



dispatch((0,_reduxBatchedActions.batchActions)([
{type:_constants.UsersTypes.RECEIVED_ME,data:data},
{type:_constants.UsersTypes.UPDATE_NOTIFY_PROPS_SUCCESS}]),
getState);case 13:case'end':return _context15.stop();}}},null,_this14,[[2,8]]);};

}exports.default=

{
checkMfa:checkMfa,
login:login,
logout:logout,
getProfiles:getProfiles,
getProfilesByIds:getProfilesByIds,
getProfilesInTeam:getProfilesInTeam,
getProfilesInChannel:getProfilesInChannel,
getProfilesNotInChannel:getProfilesNotInChannel,
getUser:getUser,
getUserByUsername:getUserByUsername,
getStatusesByIds:getStatusesByIds,
getSessions:getSessions,
loadProfilesForDirect:loadProfilesForDirect,
revokeSession:revokeSession,
getAudits:getAudits,
searchProfiles:searchProfiles,
startPeriodicStatusUpdates:startPeriodicStatusUpdates,
stopPeriodicStatusUpdates:stopPeriodicStatusUpdates,
updateUserNotifyProps:updateUserNotifyProps};